#ifndef LIBPHONENUMBER_SYS_C_REGEXP_ADAPTER_H
#define LIBPHONENUMBER_SYS_C_REGEXP_ADAPTER_H

#include "libphonenumber_sys_c_global.h"

extern "C" {

LIBPHONENUMBER_SYS_C_EXPORT i18n::phonenumbers::RegExpInput* libphonenumber_sys_c_i18n_phonenumbers_AbstractRegExpFactory_CreateInput(const i18n::phonenumbers::AbstractRegExpFactory* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* utf8_input);
LIBPHONENUMBER_SYS_C_EXPORT i18n::phonenumbers::RegExp* libphonenumber_sys_c_i18n_phonenumbers_AbstractRegExpFactory_CreateRegExp(const i18n::phonenumbers::AbstractRegExpFactory* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* utf8_regexp);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_AbstractRegExpFactory_delete(i18n::phonenumbers::AbstractRegExpFactory* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_AbstractRegExpFactory_destructor(i18n::phonenumbers::AbstractRegExpFactory* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* libphonenumber_sys_c_i18n_phonenumbers_RegExpInput_ToString_as_ptr(const i18n::phonenumbers::RegExpInput* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_RegExpInput_ToString_to_output(const i18n::phonenumbers::RegExpInput* this_ptr, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* output);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_RegExpInput_delete(i18n::phonenumbers::RegExpInput* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_RegExpInput_destructor(i18n::phonenumbers::RegExpInput* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Consume_input_string(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Consume_input_string_anchor_at_start_matched_string1_matched_string2_matched_string3(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string, bool anchor_at_start, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string1, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string2, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string3);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Consume_input_string_matched_string(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Consume_input_string_matched_string1_matched_string2(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string1, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string2);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Consume_input_string_matched_string1_matched_string2_matched_string3(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string1, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string2, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string3);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_FindAndConsume(const i18n::phonenumbers::RegExp* this_ptr, i18n::phonenumbers::RegExpInput* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_FullMatch_input_string(const i18n::phonenumbers::RegExp* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* input_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_FullMatch_input_string_matched_string(const i18n::phonenumbers::RegExp* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_GlobalReplace(const i18n::phonenumbers::RegExp* this_ptr, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* string_to_process, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* replacement_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Match(const i18n::phonenumbers::RegExp* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* input_string, bool full_match, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_PartialMatch_input_string(const i18n::phonenumbers::RegExp* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* input_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_PartialMatch_input_string_matched_string(const i18n::phonenumbers::RegExp* this_ptr, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* input_string, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* matched_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Replace_string_to_process_global_replacement_string(const i18n::phonenumbers::RegExp* this_ptr, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* string_to_process, bool global, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* replacement_string);
LIBPHONENUMBER_SYS_C_EXPORT bool libphonenumber_sys_c_i18n_phonenumbers_RegExp_Replace_string_to_process_replacement_string(const i18n::phonenumbers::RegExp* this_ptr, std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* string_to_process, const std::__cxx11::basic_string< char, std::char_traits< char >, std::allocator< char > >* replacement_string);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_RegExp_delete(i18n::phonenumbers::RegExp* this_ptr);
LIBPHONENUMBER_SYS_C_EXPORT void libphonenumber_sys_c_i18n_phonenumbers_RegExp_destructor(i18n::phonenumbers::RegExp* this_ptr);

} // extern "C"

#endif // LIBPHONENUMBER_SYS_C_REGEXP_ADAPTER_H
